version: '3.8'

services:
  app:
    container_name: app.nestguards
    build:
      context: ./
    ports:
      - '9090:9090'
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: db.nestguards
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nestguards
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
